import { SoapSection } from '../interfaces/soap-note.interface';

export const SOAP_KEYWORDS: Record<SoapSection, string[]> = {
  subjective: [
    "j'ai mal",
    'douleur',
    'douleurs',
    'gêne',
    'inconfort',
    'raideur',
    'fatigue',
    "je n'arrive plus",
    "j'ai du mal",
    'je ne peux plus',
    'je ressens',
    'brûlure',
    'picotement',
    'engourdissement',
    'fourmillement',
    'irradiant',
    'irradie',
    'depuis',
    'semaines',
    'mois',
    'se plaint',
    'plainte',
    'opéré',
    'accident',
    'chute',
    'antécédent',
    'le patient',
    'la patiente',
    'il a mal',
    'elle a mal',
    'il ressent',
    'elle ressent',
    'il décrit',
    'elle décrit',
    'il rapporte',
    'elle rapporte',
    'il se plaint',
    'elle se plaint',
    "il n'arrive plus",
    "elle n'arrive plus",
    'sa douleur',
    'ses douleurs',
    'sa gêne',
    'il souffre',
    'elle souffre',
    'quotidien',
    'habitude',
  ],
  objective: [
    'palpation',
    'inspection',
    'observation',
    'on note',
    'on observe',
    'on constate',
    'amplitude',
    'mobilité',
    'flexion',
    'extension',
    'rotation',
    'abduction',
    'adduction',
    'inclinaison',
    'testing',
    'force musculaire',
    'bilan musculaire',
    'contracture',
    'tension musculaire',
    'tonus',
    'oedème',
    'gonflement',
    'chaleur',
    'rougeur',
    'cicatrice',
    'sa posture',
    'son attitude',
    'il présente',
    'elle présente',
    'il montre',
    'elle montre',
    'sa morphologie',
    'son appui',
    'posture',
    'déséquilibre',
    'scoliose',
    'marche',
    'boiterie',
    'appui',
    'degrés',
    'bilatéral',
    'unilatéral',
    'limitée',
    'limité',
    'réflexe',
    'sensibilité',
  ],
  assessment: [
    'diagnostic',
    'syndrome',
    'pathologie',
    'lombalgie',
    'cervicalgie',
    'dorsalgie',
    'tendinite',
    'tendinopathie',
    'entorse',
    'lésion',
    'rupture',
    'limitation',
    'dysfonction',
    'insuffisance',
    'bilan montre',
    'évaluation',
    'radiculaire',
    'irritatif',
    'chronique',
    'aigu',
    'capsulite',
    'épicondylite',
    'bursite',
    'hernie',
  ],
  plan: [
    'prescris',
    'prescrit',
    'préconise',
    'recommande',
    'lui prescrire',
    'lui recommander',
    'lui conseiller',
    'lui proposer',
    'il faudra',
    'il va falloir',
    'on va',
    'il doit',
    'elle doit',
    'il devra',
    'elle devra',
    'séances',
    'kinésithérapie',
    'rééducation',
    'exercices',
    'renforcement',
    'étirements',
    'étirement',
    'mobilisations',
    'massage',
    'manipulation',
    'programme',
    'protocole',
    'revoir',
    'prochain rendez-vous',
    'à domicile',
    'auto-exercices',
    'électrothérapie',
    'ultrasons',
    'cryothérapie',
  ],
  other: [],
};
