import { SoapSection } from '../interfaces/soap-note.interface';

/**
 * French physiotherapy lexicon for keyword scoring (fixtures/product strings stay French).
 * Matching is a plain lowercase substring test: "douleur" also covers "douleurs", and a keyword
 * must not be a fragment of an unrelated word (hence "aiguë" rather than "aigu", which hits "aiguille").
 * Keep each keyword in one section only; the spec checks that every keyword resolves to its own section.
 */
export const SOAP_KEYWORDS: Record<SoapSection, string[]> = {
  subjective: [
    // pain and sensations reported by the patient
    "j'ai mal",
    'a mal',
    'fait mal',
    'fait très mal',
    'mal aux',
    'ça brûle',
    'douleur',
    'douleurs',
    'gêne',
    'gêné',
    'inconfort',
    'raideur',
    'fatigue',
    'lourdeur',
    'jambes lourdes',
    'brûlure',
    'picotement',
    'engourdissement',
    'engourdi',
    'fourmillement',
    'paresthésie',
    'décharges électriques',
    'coup de poignard',
    'élancement',
    'lancinant',
    'tiraillement',
    'ça tire',
    'ça pince',
    'ça accroche',
    'crampe',
    'craque',
    'blocage',
    'se bloque',
    'irradiant',
    'irradie',
    'irradiation',
    'nocturne',
    'la nuit',
    'réveil',
    'insomnie',
    'sommeil',
    'dort',
    'dormir',
    'ne dors',
    'par nuit',
    'essouffl',
    // how the patient describes it, in first or third person
    "je n'arrive plus",
    "j'ai du mal",
    'a du mal',
    'je ne peux plus',
    'ne peut plus',
    "n'arrive pas",
    'je ressens',
    'il ressent',
    'elle ressent',
    'il décrit',
    'elle décrit',
    'il rapporte',
    'elle rapporte',
    'il se plaint',
    'elle se plaint',
    'se plaint',
    'plainte',
    'signale',
    'me dit',
    "j'ai l'impression",
    'ne répond plus',
    'je porte',
    'raconte',
    'déclare',
    'dit avoir',
    'il souffre',
    'elle souffre',
    'difficulté',
    'impossible de',
    'incapable',
    "il n'arrive plus",
    "elle n'arrive plus",
    'sa douleur',
    'ses douleurs',
    'sa gêne',
    'il a mal',
    'elle a mal',
    // course, triggers and modulating factors
    'depuis',
    'apparu',
    'apparaît',
    'survenu',
    'brutalement',
    'récemment',
    'aggrav',
    'empire',
    'soulagement',
    'soulagé',
    'ça soulage',
    'le matin',
    'le soir',
    'en fin de journée',
    // history and context
    'antécédent',
    'opéré',
    'opération',
    'intervention chirurgicale',
    'post-opératoire',
    'postopératoire',
    'suites opératoires',
    'ostéosynthèse',
    'arthroplastie',
    'ligamentoplastie',
    'méniscectomie',
    'discectomie',
    'arthrodèse',
    'arthroscopie',
    'prothèse de hanche',
    'prothèse de genou',
    'prothèse totale',
    'plâtre',
    'accident',
    'chute',
    'tombé',
    'traumatisme',
    'faux mouvement',
    'faux pas',
    'métier',
    'profession',
    'poste de travail',
    'au travail',
    'porte des charges',
    'port de charges',
    'sédentaire',
    'sportif',
    'quotidien',
    'habitude',
    'loisirs',
    'conduire',
    'se pencher',
    'se baisser',
    // medication taken by the patient
    'anti-inflammatoire',
    'des antalgiques',
    'un antalgique',
    'paracétamol',
    'ibuprofène',
    'doliprane',
    'corticoïde',
    'médicament',
    // feelings, worries and goals
    'inquiet',
    'inquiète',
    "m'inquiète",
    'anxieu',
    'anxiété',
    'angoisse',
    'stress',
    'peur',
    'appréhension',
    'découragé',
    'mon objectif',
    'aimerait',
    'voudrait',
    'souhaite',
    'espère',
    'échelle visuelle analogique',
    // sources, sprains and falls, pelvic floor, pregnancy, respiratory
    "d'après le patient",
    'selon le patient',
    'selon elle',
    'selon lui',
    'a lâché',
    'dérob',
    'tordu',
    'foulé',
    'vertige',
    'étourdissement',
    "perte d'équilibre",
    'peur de tomber',
    'fuite',
    'envie pressante',
    'pesanteur',
    'constipation',
    'grossesse',
    'enceinte',
    'post-partum',
    'accouchement',
    'césarienne',
    'épisiotomie',
    'ménopause',
    'tousse',
    'crache',
    'crachat',
  ],
  objective: [
    // inspection
    'inspection',
    'observation',
    'on note',
    'on observe',
    'on constate',
    'on retrouve',
    'on relève',
    'on remarque',
    'on met en évidence',
    'il présente',
    'elle présente',
    'il montre',
    'elle montre',
    'examen clinique',
    'bilan musculaire',
    'bilan neurologique',
    'bilan postural',
    'bilan fonctionnel',
    'tuméfaction',
    'gonflement',
    'oedème',
    'œdème',
    'godet',
    'épanchement',
    'choc rotulien',
    'hématome',
    'ecchymose',
    'chaleur',
    'rougeur',
    'érythème',
    'cicatrice',
    'cicatrisation',
    'adhérence',
    'fibrose',
    'induration',
    'nodule',
    'trophicité',
    'amyotrophie',
    'atrophie',
    'hypotrophie',
    'fonte musculaire',
    // palpation and muscle tone
    'palpation',
    'palpable',
    'à la pression',
    'point douloureux',
    'zone douloureuse',
    'point gâchette',
    'trigger point',
    'contracture',
    'tension musculaire',
    'défense musculaire',
    'tonus',
    'hypertonie',
    'hypotonie',
    'spasticité',
    'sensibilité',
    'hypoesthésie',
    'hyperesthésie',
    'allodynie',
    'hyperalgie',
    // range of motion
    'amplitude',
    'mobilité',
    'flexion',
    'extension',
    'rotation',
    'abduction',
    'adduction',
    'inclinaison',
    'latéroflexion',
    'antépulsion',
    'rétropulsion',
    'supination',
    'pronation',
    'circumduction',
    'degrés',
    'goniom',
    'limité',
    'limitée',
    'ankylose',
    'enraidissement',
    'butée',
    'fin de course',
    'en passif',
    'en actif',
    'laxité',
    'tiroir antérieur',
    'tiroir postérieur',
    'lachman',
    'pivot shift',
    'bâillement',
    // strength and neurological examination
    'testing',
    'force musculaire',
    'cotation',
    'coté',
    'dynamom',
    'déficit de force',
    'déficit moteur',
    'faiblesse musculaire',
    'réflexe',
    'ostéotendineux',
    'babinski',
    'hoffmann',
    'clonus',
    'dermatome',
    'myotome',
    // named tests and signs
    'lasègue',
    'slump',
    'bragard',
    'tinel',
    'phalen',
    'spurling',
    'romberg',
    'trendelenburg',
    'neer',
    'hawkins',
    'jobe',
    'test de patte',
    'test de gerber',
    'test de speed',
    'yergason',
    'test de thomas',
    "test d'ober",
    'test de noble',
    'mcmurray',
    'thessaly',
    'appley',
    'steinmann',
    'valsalva',
    'schober',
    'sorensen',
    'finkelstein',
    'cozen',
    'test de mills',
    'homans',
    'timed up and go',
    'doigts-sol',
    'est positif',
    'est positive',
    'est négatif',
    'est négative',
    // posture and gait
    'posture',
    'sa posture',
    'attitude',
    'sa morphologie',
    'statique',
    'cyphose',
    'lordose',
    'scoliotique',
    'gibbosité',
    "test d'adams",
    'valgus',
    'varus',
    'valgum',
    'varum',
    'recurvatum',
    'flessum',
    'antéversion',
    'rétroversion',
    'asymétrie',
    'déviation',
    'ascension',
    'antéprojection',
    'enroulement',
    'pied plat',
    'pied creux',
    'bascule du bassin',
    'dyskinési',
    'marche',
    'boiterie',
    'steppage',
    'fauchage',
    'appui',
    'son appui',
    'déséquilibre',
    'bilatéral',
    'unilatéral',
    // measurements
    'périmètre',
    'circonférence',
    'mensuration',
    'mètre ruban',
    'centimètre',
    'longueur des membres',
    'saturation',
    'spo2',
    'fréquence cardiaque',
    'fréquence respiratoire',
    'auscultation',
    'sibilants',
    'crépitants',
    'râles',
    // pelvic floor, lymphoedema, paediatrics, geriatrics, respiratory and neurological findings
    'diastasis',
    'contraction du plancher',
    'contraction périnéale',
    'contraction du périnée',
    'testing périnéal',
    'toucher vaginal',
    'toucher rectal',
    'tonicité',
    'stemmer',
    "peau d'orange",
    'volumétrie',
    'tenue de tête',
    'archaïque',
    'angle de cobb',
    'risser',
    'tinetti',
    'échelle de berg',
    'lever de chaise',
    'murmure vésiculaire',
    'ronflants',
    'expansion thoracique',
    'tirage',
    'cyanose',
    'battement des ailes du nez',
    'spirométrie',
    'capacité vitale',
    'peak flow',
    'héminégligence',
    'ataxie',
    'dysarthrie',
    'dysmétrie',
    'nystagmus',
    'syncinési',
    'ashworth',
    'tardieu',
    'barthel',
    'nihss',
    'glasgow',
  ],
  assessment: [
    // clinical reasoning
    'diagnostic',
    'hypothèse',
    'suspicion',
    'suspect',
    'probable',
    'évoque',
    'compatible',
    'en faveur',
    'conclusion',
    'bilan montre',
    'pronostic',
    'favorable',
    'origine',
    'étiologie',
    'en rapport avec',
    'secondaire à',
    'consécutif',
    'imputable',
    'séquelle',
    'séquellaire',
    'atteinte',
    'déficience',
    'incapacité',
    'limitation',
    'limitation fonctionnelle',
    'déconditionnement',
    'chronicité',
    'dysfonction',
    'insuffisance',
    'stade',
    'grade',
    'gravité',
    'sévér',
    'drapeau',
    'red flag',
    'yellow flag',
    'facteurs de risque',
    'facteur de risque',
    'sédentarité',
    'surpoids',
    'obésité',
    'tabagisme',
    'diabète',
    'diabétique',
    'chronique',
    'aiguë',
    'subaigu',
    'récidiv',
    'dégénérati',
    'inflammation',
    'traumatique',
    'neuropathique',
    'nociceptif',
    'sensibilisation centrale',
    'kinésiophobie',
    'catastrophisme',
    'irritatif',
    'radiculaire',
    // spine
    'syndrome',
    'pathologie',
    'lombalgie',
    'lumbago',
    'sciatique',
    'sciatalgie',
    'cruralgie',
    'radiculalgie',
    'radiculopathie',
    'névralgie',
    'cervicalgie',
    'dorsalgie',
    'torticolis',
    'coup du lapin',
    'whiplash',
    'arthrose',
    'arthrite',
    'discopathie',
    'hernie',
    'protrusion',
    'spondylolisthésis',
    'spondylolyse',
    'spondylose',
    'canal lombaire étroit',
    'sténose',
    'scoliose',
    'ostéoporose',
    'ostéopénie',
    'algodystrophie',
    'fibromyalgie',
    // shoulder, elbow, hand
    'coiffe des rotateurs',
    'conflit sous-acromial',
    'capsulite',
    'rétractile',
    'épaule gelée',
    'épicondylite',
    'épitrochléite',
    'tennis elbow',
    'canal carpien',
    'de quervain',
    'dupuytren',
    'doigt à ressort',
    // hip, knee, ankle, foot
    'coxalgie',
    'conflit fémoro-acétabulaire',
    'gonalgie',
    'pubalgie',
    'talalgie',
    'métatarsalgie',
    'névrome de morton',
    'épine calcanéenne',
    'fémoro-patellaire',
    'chondropathie',
    'chondromalacie',
    'méniscopathie',
    'ligament croisé',
    'entorse',
    'luxation',
    'fracture',
    'fracture de fatigue',
    'fissure',
    'contusion',
    'déchirure',
    'claquage',
    'élongation',
    'lésion',
    'rupture',
    // tendons, muscles, inflammation
    'tendinopathie',
    'tendinite',
    'tendinose',
    'ténosynovite',
    'synovite',
    'bursite',
    'fasciite',
    'aponévrosite',
    'périostite',
    'myosite',
    'myalgie',
    'myopathie',
    'enthésite',
    'sacro-iliite',
    'névrite',
    // neurological
    'avc',
    'hémiplégie',
    'hémiparésie',
    'paraplégie',
    'tétraplégie',
    'paralysie',
    'neuropathie',
    'sclérose en plaques',
    'parkinson',
    'guillain-barré',
    'queue de cheval',
    // respiratory and paediatric
    'bronchite',
    'bronchiolite',
    'bpco',
    'asthme',
    'pneumopathie',
    'pneumonie',
    'atélectasie',
    'mucoviscidose',
    'dysplasie',
    'plagiocéphalie',
    // pelvic floor, lymphoedema, paediatrics, geriatrics, respiratory and neurological diagnoses
    'incontinence',
    'prolapsus',
    'cystocèle',
    'rectocèle',
    'dyspareunie',
    'vaginisme',
    'endométriose',
    'lymphangite',
    'phlébite',
    'thrombose',
    'ulcère',
    'érysipèle',
    'retard psychomoteur',
    'pied bot',
    'pneumothorax',
    'embolie',
    'détresse respiratoire',
    'encombrement bronchique',
    'sarcopénie',
    'fragilité',
    'dénutrition',
    'aphasie',
    'myasthénie',
    'polyradiculonévrite',
    // judgement of progress and causal reasoning
    'évolution',
    'rassurant',
    'préoccupant',
    'inquiétant',
    'satisfaisant',
    'stagnation',
    'plateau',
    'atteint',
    'lié à',
    'liée à',
    'responsable de',
    'en lien avec',
    'est en cause',
    'expliquent',
    'semblent',
    'composante',
  ],
  plan: [
    // prescriptions, advice and intentions
    'prescris',
    'prescrit',
    'prescription',
    'ordonnance',
    'préconise',
    'préconisation',
    'recommande',
    'recommandation',
    'lui prescrire',
    'lui recommander',
    'lui conseiller',
    'lui proposer',
    'conseil',
    'consigne',
    'je vous propose',
    'nous allons',
    'on va',
    'je vais',
    'il faut',
    'il faudra',
    'il va falloir',
    'il doit',
    'elle doit',
    'il devra',
    'elle devra',
    'évit',
    'limiter',
    'ménager',
    'mise au repos',
    'repos relatif',
    'repos strict',
    'prévoi',
    'prévu',
    'envisag',
    'prise en charge',
    'plan de soins',
    'projet thérapeutique',
    // sessions and follow-up
    'séances',
    'séance de',
    'à raison de',
    'fois par semaine',
    'fois par jour',
    'tous les soirs',
    'revoir',
    'revois',
    'réévalu',
    'bilan final',
    'bilan intermédiaire',
    'bilan de fin',
    'prochain rendez-vous',
    'reprise',
    'reprise progressive',
    'reprise de la course',
    'reprise du sport',
    // exercise and rehabilitation
    'kinésithérapie',
    'rééducation',
    'réadaptation',
    'reconditionnement',
    'réentraînement',
    'exercice',
    'auto-exercices',
    "fiche d'exercices",
    'programme',
    'protocole',
    'à domicile',
    'à la maison',
    'renforcement',
    'gainage',
    'musculation',
    'étirement',
    'stretching',
    'assouplissement',
    'proprioce',
    'excentrique',
    'pliométrie',
    'travailler',
    'ventilation',
    // manual techniques and physical agents
    'mobilisations',
    'mobilisation articulaire',
    'mobilisation manuelle',
    'massage',
    'friction',
    'pétrissage',
    'drainage',
    'drainage lymphatique',
    'pressothérapie',
    'manipulation',
    'thérapie manuelle',
    'techniques manuelles',
    'contracté-relâché',
    'crochetage',
    'ventouses',
    'dry needling',
    'aiguilles sèches',
    'électrothérapie',
    'électrostimulation',
    'ultrasons',
    'ondes de choc',
    'onde de choc',
    'laser',
    'cryothérapie',
    'glace',
    'thermothérapie',
    'fango',
    'paraffine',
    'balnéothérapie',
    'hydrothérapie',
    'désencombrement',
    'aérosol',
    // strapping, aids and equipment
    'strapping',
    'kinésiotape',
    'taping',
    'bandage',
    'contention',
    'orthèse',
    'attelle',
    'semelle',
    'canne',
    'béquille',
    'mise en décharge',
    'ceinture lombaire',
    'collier cervical',
    'écharpe',
    'chaussage',
    // education and ergonomics
    'éducation',
    'ergonomi',
    'hygiène de vie',
    'hygiène posturale',
    // referral and further examinations
    'orienter',
    'adresser',
    'adressé',
    'avis médical',
    'avis spécialisé',
    'avis chirurgical',
    'médecin traitant',
    'médecin du sport',
    'rhumatologue',
    'chirurgien',
    'orthopédiste',
    'neurologue',
    'podologue',
    'ostéopathe',
    'consulter',
    'une irm',
    'une imagerie',
    'une radiographie',
    'une échographie',
    'un scanner',
    'emg',
    'électromyogramme',
    'bilan complémentaire',
    'examens complémentaires',
    'examen complémentaire',
    'bilan sanguin',
    // pelvic floor, lymphoedema, paediatrics, geriatrics, respiratory and neurological treatment
    'biofeedback',
    'hypopressi',
    'sangle',
    'agenda mictionnel',
    'hygiène mictionnelle',
    'apprenez',
    'apprendre à',
    'contracter',
    'manchon',
    'surélév',
    'soins de peau',
    'hygiène cutanée',
    'stimulation',
    'positionnement',
    'portage',
    'déambulateur',
    'rollator',
    'toux dirigée',
    'toux assistée',
    'aide à la toux',
    'oxygénothérapie',
    'expiration lente',
    'thérapie miroir',
    'bobath',
    'kabat',
    'tapis roulant',
    'toxine botulique',
  ],
  other: [],
};
